/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_d3x_osqp_OsqpModel */

#ifndef _Included_com_d3x_osqp_OsqpModel
#define _Included_com_d3x_osqp_OsqpModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_d3x_osqp_OsqpModel
 * Method:    run
 * Signature: (JJLjava/lang/String;[D[J[J[D[J[J[D[D[D[D[D[Ljava/lang/String;[D)I
 */
JNIEXPORT jint JNICALL Java_com_d3x_osqp_OsqpModel_run
  (JNIEnv *, jobject, jlong, jlong, jstring, jdoubleArray, jlongArray, jlongArray, jdoubleArray, jlongArray, jlongArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobjectArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
